In [ ]:
import numpy as np
import torch
import tensorflow as tf

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')

In [ ]:
# Target (apples)
targets = np.array(
[[56],
[81],
[119],
[22],
[103]], dtype='float32')

In [ ]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [ ]:
# Weights and biases
w = torch.randn(1, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.3748,  0.3505, -0.1131]], requires_grad=True)
tensor([ 1.8889, -0.3614], requires_grad=True)


In [ ]:
# Define the model
def model(x):
    return x @ w.t() + b

In [ ]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[47.8761, 45.6259],
        [59.6100, 57.3597],
        [74.9134, 72.6632],
        [51.0125, 48.7623],
        [53.4891, 51.2388]], grad_fn=<AddBackward0>)


In [ ]:
# Compare with targets
print(targets)

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [ ]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [ ]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(1196.9230, grad_fn=<DivBackward0>)


In [ ]:
# Compute gradients
loss.backward()

In [ ]:
# Gradients for weights
print("Gradients for weights")
print(w)
print(w.grad)

# Gradients for bias
print("\nGradients for bias")
print(b)
print(b.grad)

Gradients for weights
tensor([[ 0.3748,  0.3505, -0.1131]], requires_grad=True)
tensor([[-2922.7378, -4928.5127, -2789.4573]])

Gradients for bias
tensor([ 1.8889, -0.3614], requires_grad=True)
tensor([-18.8198, -21.0700])


In [ ]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.]])
tensor([0., 0.])


In [ ]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[47.8761, 45.6259],
        [59.6100, 57.3597],
        [74.9134, 72.6632],
        [51.0125, 48.7623],
        [53.4891, 51.2388]], grad_fn=<AddBackward0>)


In [ ]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(1196.9230, grad_fn=<DivBackward0>)


In [ ]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-2922.7378, -4928.5127, -2789.4573]])
tensor([-18.8198, -21.0700])


In [ ]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

print(w)
print(b)

tensor([[ 0.4041,  0.3998, -0.0852]], requires_grad=True)
tensor([ 1.8890, -0.3611], requires_grad=True)


In [ ]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(860.8496, grad_fn=<DivBackward0>)


In [ ]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [ ]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(80.7273, grad_fn=<DivBackward0>)


In [ ]:
# Predictions
preds

tensor([[ 61.0159,  58.7679],
        [ 80.8527,  78.6048],
        [121.0719, 118.8240],
        [ 36.8773,  34.6293],
        [ 90.3216,  88.0737]], grad_fn=<AddBackward0>)

In [ ]:
# Targets
targets

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])