In [2]:
# Import Numpy & PyTorch
import numpy as np
import torch
# Imports
import torch.nn as nn

In [3]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [4]:
from torch.utils.data import TensorDataset

In [5]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[1:3]

(tensor([[ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 81., 101.],
         [119., 133.]]))

In [6]:
from torch.utils.data import DataLoader

# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 87., 134.,  58.],
        [ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [ 87., 134.,  58.],
        [ 73.,  67.,  43.]])
tensor([[119., 133.],
        [ 81., 101.],
        [ 22.,  37.],
        [119., 133.],
        [ 56.,  70.]])


In [7]:
# Define model
model = nn.Linear(3, 2)
print("Weight : ",model.weight)
print("Bias : ",model.bias)

Weight :  Parameter containing:
tensor([[ 0.4938,  0.0115,  0.1191],
        [-0.2596, -0.1110, -0.3814]], requires_grad=True)
Bias :  Parameter containing:
tensor([ 0.2360, -0.2112], requires_grad=True)


In [8]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.4938,  0.0115,  0.1191],
         [-0.2596, -0.1110, -0.3814]], requires_grad=True),
 Parameter containing:
 tensor([ 0.2360, -0.2112], requires_grad=True)]

In [9]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [10]:
# Import nn.functional
import torch.nn.functional as F

# Define loss function
loss_fn = F.mse_loss

In [11]:
loss = loss_fn(model(inputs), targets)
print("Loss : ",loss)

Loss :  tensor(12258.3604, grad_fn=<MseLossBackward0>)


In [12]:
# train the model
def fit(num_epochs, model, loss_fn, opt):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [13]:
# Train the model for 100 epochs
fit(100, model, loss_fn, opt)

Epoch [10/100], Loss: 331.8343
Epoch [20/100], Loss: 388.4932
Epoch [30/100], Loss: 465.2560
Epoch [40/100], Loss: 178.7986
Epoch [50/100], Loss: 100.9314
Epoch [60/100], Loss: 127.2633
Epoch [70/100], Loss: 102.7085
Epoch [80/100], Loss: 34.7784
Epoch [90/100], Loss: 32.8538
Epoch [100/100], Loss: 40.9842


In [14]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.8641,  71.3536],
        [ 81.1424,  96.5564],
        [118.1657, 138.9764],
        [ 30.6806,  44.1168],
        [ 94.5283, 107.9166],
        [ 58.8641,  71.3536],
        [ 81.1424,  96.5564],
        [118.1657, 138.9764],
        [ 30.6806,  44.1168],
        [ 94.5283, 107.9166],
        [ 58.8641,  71.3536],
        [ 81.1424,  96.5564],
        [118.1657, 138.9764],
        [ 30.6806,  44.1168],
        [ 94.5283, 107.9166]], grad_fn=<AddmmBackward0>)

In [15]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [16]:
fit(100, model, loss_fn, opt)

Epoch [10/100], Loss: 41.9499
Epoch [20/100], Loss: 42.2305
Epoch [30/100], Loss: 14.4202
Epoch [40/100], Loss: 12.5707
Epoch [50/100], Loss: 26.8560
Epoch [60/100], Loss: 19.2725
Epoch [70/100], Loss: 11.4467
Epoch [80/100], Loss: 16.6303
Epoch [90/100], Loss: 11.4606
Epoch [100/100], Loss: 14.5479
